runtime: nodejs12
service: nuxt-demo

instance_class: F2

default_expiration: 1m

vpc_access_connector:
  name: projects/parkos-staging/locations/europe-west1/connectors/nuxt-redis

# inbound_services:
#   - warmup

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: "0.0.0.0"
  REDIS_HOST: "10.0.0.3"
