runtime: custom
env: flex
service: mpl

automatic_scaling:
  min_num_instances: %%AUTOMATIC_SCALING_MIN_NUM_INSTANCES%%
  max_num_instances: %%AUTOMATIC_SCALING_MAX_NUM_INSTANCES%%
  
resources:
  cpu: %%RESOURCES_CPU%%
  memory_gb: %%RESOURCES_MEMORY_GB%%

env_variables:
  NODE_ENV: %%NODE_ENV%%
  API_BASE_URL: "%%API_BASE_URL%%"
  GOOGLE_MAPS_API_KEY: "%%GOOGLE_MAPS_API_KEY%%"
  SENTRY_DSN: "%%SENTRY_DSN%%"
  ZENDESK_KEY: "%%ZENDESK_KEY%%"