runtime: custom
env: flex
service: mpl

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4

resources:
  cpu: 2
  memory_gb: 2

env_variables:
  NODE_ENV: "production"
  API_BASE_URL: "https://parkos.com/api/v1/"
  GOOGLE_MAPS_API_KEY: "AIzaSyDTlDjkPhINXUcc_f_Za3Xd7-hE7GXXzd0"
  SENTRY_DSN: "https://0e3735aa960a4212bcbfdd70bae9f66e@o109164.ingest.sentry.io/5699581"
  ZENDESK_KEY: "2a147e2d-9a66-4262-92ee-9e02607930a7"