runtime: custom
env: flex
service: mpl-airport-page
manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.9

env_variables:
  NODE_ENV: production
  API_BASE_URL: "https://parkos.test/api/v1/"
  GOOGLE_MAPS_API_KEY:''
  SENTRY_DSN: ''
  ZENDESK_KEY: ''
