name: JIRA

on:
  pull_request:
    types: [ready_for_review]

jobs:
  build:
    name: Set issue status to 'Code Review'
    runs-on: ubuntu-latest
    steps:
      - name: JIRA Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find issue key
        id: find_issue_key
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ github.event.pull_request.title }}
          from: ""
      - name: Set issue status
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.find_issue_key.outputs.issue }}
          transition: "Code Review"
